### ISSUE TITLE
[Bug] ... Disconnect to server (1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [SuperMartijn642/SuperMartijn642sConfigLib#6] opened 2022-06-07 13:12 UTC
Hello!
If your mod is updated from the version "supermartijn642configlib-1.0.9a-mc1.12.jar" to "supermartijn642configlib-1.1.0-forge-mc1.12.jar" and higher (and on the server too), then when you try to enter the server there is a disconnect (not a crash).
I am attaching the log file (client).
Thank you for your attention!
[2022-06-07-2.log](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/8853453/2022-06-07-2.log)

**Comment by SuperMartijn642** [comment] 2022-06-07 14:27
Looking at the log file, the only mod installed using my config library is Moving Elevators.
I can connect to a server fine when my config library, core library, and Moving Elevators are installed on both sides.

Could you check if the disconnect is actually caused by Moving Elevators and my config library?
If so, could you narrow down the other mods needed for the disconnect to occur? (Since you have quite a lot of mods loaded)

---
As a side note, metamorph is completely spamming the console with errors. You should probably report those errors to them with the same log you gave me.

**Comment by SeagalKru** [comment] 2022-06-07 14:46
(Google translation from Russia)

Good. According to Metamorph, I'll send them a log file.
But this mod is only on my client, it is not used on the server.
According to your mod:
now I have reverted the "supermartijn642configlib-1.0.9a-mc1.12.jar" version to both client and server: both work.
even if your mod is updated to the latest version "supermartijn642configlib-1.1.1-forge-mc1.12.jar" both on the server and on the client: they both load and work.
But with your updated mod, when I try to enter the server, it turns out that I go to it and I immediately get kicked from it (disconnect) and display it on the screen (without closing the game) with the error "The received string length is longer than maximum allowed (32 > 20)".

**Comment by SuperMartijn642** [comment] 2022-06-07 18:08
I finally found the issue, seems network channel names need to be less than 20 characters in 1.12 for some reason. Not entirely sure why it isn't enforced in my dev environment though.

It should be fixed now in my config library 1.1.1a for Minecraft 1.12.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2022-06-07 18:08 UTC
Labels: bug
