### ISSUE TITLE
[Bug] world loading stops during fresh world creation

### ISSUE THREAD

**Issue by NighthowlerStudios** [SuperMartijn642/SuperMartijn642sConfigLib#8] opened 2022-07-03 16:02 UTC
**Version Info**
- Minecraft,1.16.5
- Config Lib, 1.1.X

**Description of the Bug**
Downgrading to config lib 1.0.9 sees the issue disappear.  In 1.1.X, it will give a chance to prevent a world from loading by simply stopping after a few chunks are done if it does not reach the chunk rendering stage of world loading.  it seems to be an issue specifically preventing the client thread from moving forward

**Steps to Reproduce**
Download Kaleidio's Battle Pack 4.3.6
Attempt to upgrade config lib to anything 1.1.X
Generate a new world, attempt twice if needed, world has a chance here to not pass the loading screen but a multiplayer server would enter the world as intended.

**Comment by SuperMartijn642** [comment] 2022-07-03 16:58
This has nothing to do with what was fixed in version 1.1.3. The issue fixed in version 1.1.3 was the file watcher thread staying active when the game was closed, thus preventing the program from stopping. The thread was not locked up, it was just continuing to watch files.
There is also no way for the file watcher thread to prevent a world from loading.

Kaleidio's Battle Pack has a lot of mods. What makes you think the issue is caused by my config library? Can you replicate the issue with only my config library and the mods that depend on it?

**Comment by NighthowlerStudios** [comment] 2022-07-03 18:51
> Kaleidio's Battle Pack has a lot of mods. What makes you think the issue is caused by my config library? Can you replicate the issue with only my config library and the mods that depend on it?

In my pack it only locks up if your mod is up to 1.1.X.  as mentioned before downgrading to 1.0.9 fixes the issue.

I am aware there is a lot of mods.  If you wish for me to go through a mod "binary search" to find a conflict, I will do so.

Edited original post to clarify and simplify the issue details

**Comment by NighthowlerStudios** [comment] 2022-07-06 16:16
I am having trouble finding the conflicting mod, but I can confirm it does not happen on its own, only when it's up to date alongside the modpack.  I will continue searching for the conflict but it may take me a long whilst alongside all other developments I'm doing

**Closed as completed** 2023-03-05 20:55 UTC
Labels: bug
